server.port=8081
spring.application.name=BeautyFlowCadastro-service
spring.data.mongodb.uri=mongodb://localhost:27017/beautyflow_cadastro
spring.data.mongodb.database=beautyflow_cadastro
logging.level.com.beautyflow=DEBUG