server.port=8082
spring.application.name=scheduling-service
spring.data.mongodb.uri=mongodb://localhost:27017/beautyflow_agendamento
spring.data.mongodb.database=beautyflow_agendamento
logging.level.com.example=DEBUG